name: merge

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: LS
      run: |
        pwd
        ls
        cd ..
        pwd
        ls
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install deps
      run: |
        pwd
        ls
        npm install
    - name: LS
      run: |
        pwd
        ls
    - name: clone rocket.chat
      uses: actions/checkout@master
      with:
        repository: RocketChat/Rocket.Chat.ReactNative
        path: ..
    - name: merge styles
      run: |
        npm run merge
    - name: build APK
      run: |
        cd Rocket.Chat.ReactNative
        yarn
        npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle
