name: merge

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      latest_version: ${{ steps.latest_version.outputs.version }}
      current_version: ${{ steps.current_version.outputs.version }}

    steps:
    - uses: actions/checkout@v2
    - name: Set Latest Release
      id: latest_version
      run: |
        git fetch --tags
        echo ::set-output name=version::$(git tag --sort=committerdate | tail -1)
    - name: Clone Rocket.Chat.ReactNative
      uses: actions/checkout@master
      with:
        repository: RocketChat/Rocket.Chat.ReactNative
        path: 'Rocket.Chat.ReactNative.Repo'
    - name: Set Current Release
      id: current_version
      run: |
        git fetch --tags
        echo ::set-output name=version::$(git tag --sort=committerdate | tail -1)
      working-directory: Rocket.Chat.ReactNative.Repo
    - name: List Releases
      run: |
        echo latest release: ${{steps.latest_version.outputs.version}}
        echo current release: ${{steps.current_version.outputs.version}}
        
  build:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.latest_version != needs.check.outputs.current_version

    steps:
    - name: Run release
      run: echo release it!
    - uses: actions/checkout@v2
    - name: Clone Rocket.Chat.ReactNative
      uses: actions/checkout@master
      with:
        repository: RocketChat/Rocket.Chat.ReactNative
        path: 'Rocket.Chat.ReactNative.Repo'
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Dependencies
      run: |
        npm install
    - name: merge styles
      run: |
        npm run merge ./Rocket.Chat.ReactNative.Repo
    - name: React Native Bundle
      run: |
        yarn && npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle
      working-directory: Rocket.Chat.ReactNative.Repo
    - name: Setup Keystore
      run: |
        echo "${{ secrets.KEYSTORE }}" > release.b64
        base64 -d release.b64 > android/app/release.keystore
      working-directory: Rocket.Chat.ReactNative.Repo
    - name: Build and Sign APK
      uses: eskatos/gradle-command-action@v1
      with:
        wrapper-directory: Rocket.Chat.ReactNative.Repo/android
        build-root-directory: Rocket.Chat.ReactNative.Repo/android
        arguments: assembleOfficialFossRelease
          -PKEYSTORE=release.keystore
          -PKEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
          -PKEY_ALIAS=${{ secrets.KEY_ALIAS }}
          -PKEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
          tag_name: ${{ needs.check.outputs.current_version }}
          release_name: ${{ needs.check.outputs.current_version }}
          body: |
            RocketChat.ReactNative Version ${{ needs.check.outputs.current_version }}
          draft: false
          prerelease: false
    - name: Find Artifact
      run: |
        echo *** root;
        ls;
        echo ***
        echo *** Rocket.Chat.ReactNative.Repo;
        cd Rocket.Chat.ReactNative.Repo;
        ls;
        echo *** android;
        cd android;
        ls;
        echo ***;
        echo *** app/build;
        cd app/build;
        ls;
        echo ***;
        echo *** outputs;
        cd outputs;
        ls;
        echo ***;
        echo *** apk;
        cd apk;
        ls;
        echo ***;
        echo *** officialFoss;
        cd officialFoss;
        ls;
        echo ***;
        echo *** release;
        cd release;
        ls;
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: app-official-foss-release
        path: Rocket.Chat.ReactNative.Repo/android/app/build/outputs/apk/officialFoss/release
