name: merge

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Dependencies
      run: |
        npm install
    - name: Clone Rocket.Chat.ReactNative
      uses: actions/checkout@master
      with:
        repository: RocketChat/Rocket.Chat.ReactNative
        path: 'Rocket.Chat.ReactNative.Repo'
    - name: merge styles
      run: |
        pwd
        echo --------------
        ls Rocket.Chat.ReactNative.Repo
        echo ---------------
        cat Rocket.Chat.ReactNative.Repo/app.json
        ls
        npm run merge ./Rocket.Chat.ReactNative.Repo
    - name: build APK
      run: |
        cd Rocket.Chat.ReactNative
        yarn
        npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle
