name: merge

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Latest Release
      id: latest_version
      run: |
        git fetch --tags
        echo ::set-output name=version::$(git tag --sort=committerdate | tail -1)
    - name: Clone Rocket.Chat.ReactNative
      uses: actions/checkout@master
      with:
        repository: RocketChat/Rocket.Chat.ReactNative
        path: 'Rocket.Chat.ReactNative.Repo'
    - name: Set Current Release
      id: current_version
      run: |
        git fetch --tags
        echo ::set-output name=version::$(git tag --sort=committerdate | tail -1)
      working-directory: Rocket.Chat.ReactNative.Repo
    - name: List Releases
      run: |
        echo latest release: ${{steps.latest_version.outputs.version}}
        echo current release: ${{steps.current_version.outputs.version}}
    - name: Check Release
      if: steps.latest_version.outputs.version == steps.current_version.outputs.version
      run: |
        exit 1
    # - name: Use Node.js
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: '14.x'
    # - name: set up JDK 1.8
    #   uses: actions/setup-java@v1
    #   with:
    #     java-version: 1.8
    # - name: Install Dependencies
    #   run: |
    #     npm install
    # - name: merge styles
    #   run: |
    #     npm run merge ./Rocket.Chat.ReactNative.Repo
    # - name: React Native Bundle
    #   run: |
    #     cd Rocket.Chat.ReactNative.Repo
    #     yarn && npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle
    # - name: Build and Sign APK
    #   uses: eskatos/gradle-command-action@v1
    #   with:
    #     wrapper-directory: Rocket.Chat.ReactNative.Repo/android
    #     build-root-directory: Rocket.Chat.ReactNative.Repo/android
    #     arguments: assembleOfficialFossRelease
    #       -PKEYSTORE=${{ secrets.KEYSTORE }}
    #       -PKEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
    #       -PKEY_ALIAS=${{ secrets.KEY_ALIAS }}
    #       -PKEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
    #     wrapper-cache-enabled: true
    #     dependencies-cache-enabled: true
    #     configuration-cache-enabled: true
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
          tag_name: ${{ steps.current_version.outputs.version }}
          release_name: ${{ steps.current_version.outputs.version }}
          body: |
            RocketChat.ReactNative Version ${{ steps.current_version.outputs.version }}
          draft: false
          prerelease: false 
